# Generated by Django 6.1.1 on 2026-09-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('schedule', models.JSONField(default=dict)),
                ('closed_message', models.CharField(blank=True, default='Website will be opened soon, please wait a moment or call +2349072825649 for enquiries.', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
